import { z } from 'zod';
export declare const createTransactionSchema: z.ZodObject<{
    id: z.ZodString;
    branchId: z.ZodString;
    customerId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    customerName: z.ZodOptional<z.ZodString>;
    customerPhone: z.ZodOptional<z.ZodString>;
    subtotal: z.ZodNumber;
    discount: z.ZodDefault<z.ZodNumber>;
    tax: z.ZodDefault<z.ZodNumber>;
    total: z.ZodNumber;
    paymentMethod: z.ZodString;
    items: z.ZodArray<z.ZodObject<{
        productId: z.ZodString;
        price: z.ZodNumber;
        discount: z.ZodDefault<z.ZodNumber>;
        subtotal: z.ZodNumber;
    }, z.core.$strip>>;
    promoCode: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    promoCampaignId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    splitPayments: z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodObject<{
        method: z.ZodString;
        amount: z.ZodNumber;
    }, z.core.$strip>>>>;
    leadSource: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    closingType: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    overrideToken: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>;
//# sourceMappingURL=transaction.validation.d.ts.map