"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const b2b_controller_1 = require("../controllers/b2b.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.use(auth_middleware_1.authenticateJWT);
router.get('/metrics', (0, auth_middleware_1.requirePermission)('B2B.View'), b2b_controller_1.getB2BMetrics);
router.get('/partners', (0, auth_middleware_1.requirePermission)('B2B.View'), b2b_controller_1.getPartners);
router.post('/partners', (0, auth_middleware_1.requirePermission)('B2B.Manage'), b2b_controller_1.createPartner);
router.patch('/partners/:id', (0, auth_middleware_1.requirePermission)('B2B.Manage'), b2b_controller_1.updatePartner);
router.delete('/partners/:id', (0, auth_middleware_1.requirePermission)('B2B.Manage'), b2b_controller_1.deletePartner);
router.get('/activities', (0, auth_middleware_1.requirePermission)('B2B.View'), b2b_controller_1.getActivities);
router.post('/activities', (0, auth_middleware_1.requirePermission)('B2B.Manage'), b2b_controller_1.createActivity);
router.get('/schedules', (0, auth_middleware_1.requirePermission)('B2B.View'), b2b_controller_1.getSchedules);
router.post('/schedules', (0, auth_middleware_1.requirePermission)('B2B.Manage'), b2b_controller_1.createSchedule);
router.post('/schedules/batch', (0, auth_middleware_1.requirePermission)('B2B.Manage'), b2b_controller_1.createBatchSchedules);
router.get('/transactions', (0, auth_middleware_1.requirePermission)('B2B.View'), b2b_controller_1.getTransactions);
router.post('/transactions', (0, auth_middleware_1.requirePermission)('B2B.Manage'), b2b_controller_1.createTransaction);
router.get('/maintenance', (0, auth_middleware_1.requirePermission)('B2B.View'), b2b_controller_1.getMaintenanceLogs);
router.post('/maintenance', (0, auth_middleware_1.requirePermission)('B2B.Manage'), b2b_controller_1.createMaintenanceLog);
exports.default = router;
//# sourceMappingURL=b2b.routes.js.map